defaults: &defaults
  upload_dir: app/raw_files
  processed_dir: app/raw_files/processed
  inbound_dir: app/raw_files/inbound

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
